/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6573_MP. Copyright MediaTek Inc. (C) 2011.
 * Mon Oct 17 23:34:53 2011
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_BATTERY_VOLTAGE_CHANNEL     0
#define AUXADC_REF_CURRENT_CHANNEL     1
#define AUXADC_CHARGER_VOLTAGE_CHANNEL     2
#define AUXADC_TEMPERATURE_CHANNEL     5


#endif //_CUST_AUXADC_TOOL_H


