/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/*
 * arch/arm/mach-ep93xx/include/mach/irqs.h
 */

#ifndef __ASM_ARCH_IRQS_H
#define __ASM_ARCH_IRQS_H

#define IRQ_EP93XX_COMMRX		2
#define IRQ_EP93XX_COMMTX		3
#define IRQ_EP93XX_TIMER1		4
#define IRQ_EP93XX_TIMER2		5
#define IRQ_EP93XX_AACINTR		6
#define IRQ_EP93XX_DMAM2P0		7
#define IRQ_EP93XX_DMAM2P1		8
#define IRQ_EP93XX_DMAM2P2		9
#define IRQ_EP93XX_DMAM2P3		10
#define IRQ_EP93XX_DMAM2P4		11
#define IRQ_EP93XX_DMAM2P5		12
#define IRQ_EP93XX_DMAM2P6		13
#define IRQ_EP93XX_DMAM2P7		14
#define IRQ_EP93XX_DMAM2P8		15
#define IRQ_EP93XX_DMAM2P9		16
#define IRQ_EP93XX_DMAM2M0		17
#define IRQ_EP93XX_DMAM2M1		18
#define IRQ_EP93XX_GPIO0MUX		19
#define IRQ_EP93XX_GPIO1MUX		20
#define IRQ_EP93XX_GPIO2MUX		21
#define IRQ_EP93XX_GPIO3MUX		22
#define IRQ_EP93XX_UART1RX		23
#define IRQ_EP93XX_UART1TX		24
#define IRQ_EP93XX_UART2RX		25
#define IRQ_EP93XX_UART2TX		26
#define IRQ_EP93XX_UART3RX		27
#define IRQ_EP93XX_UART3TX		28
#define IRQ_EP93XX_KEY			29
#define IRQ_EP93XX_TOUCH		30
#define EP93XX_VIC1_VALID_IRQ_MASK	0x7ffffffc

#define IRQ_EP93XX_EXT0			32
#define IRQ_EP93XX_EXT1			33
#define IRQ_EP93XX_EXT2			34
#define IRQ_EP93XX_64HZ			35
#define IRQ_EP93XX_WATCHDOG		36
#define IRQ_EP93XX_RTC			37
#define IRQ_EP93XX_IRDA			38
#define IRQ_EP93XX_ETHERNET		39
#define IRQ_EP93XX_EXT3			40
#define IRQ_EP93XX_PROG			41
#define IRQ_EP93XX_1HZ			42
#define IRQ_EP93XX_VSYNC		43
#define IRQ_EP93XX_VIDEO_FIFO		44
#define IRQ_EP93XX_SSP1RX		45
#define IRQ_EP93XX_SSP1TX		46
#define IRQ_EP93XX_GPIO4MUX		47
#define IRQ_EP93XX_GPIO5MUX		48
#define IRQ_EP93XX_GPIO6MUX		49
#define IRQ_EP93XX_GPIO7MUX		50
#define IRQ_EP93XX_TIMER3		51
#define IRQ_EP93XX_UART1		52
#define IRQ_EP93XX_SSP			53
#define IRQ_EP93XX_UART2		54
#define IRQ_EP93XX_UART3		55
#define IRQ_EP93XX_USB			56
#define IRQ_EP93XX_ETHERNET_PME		57
#define IRQ_EP93XX_DSP			58
#define IRQ_EP93XX_GPIO_AB		59
#define IRQ_EP93XX_SAI			60
#define EP93XX_VIC2_VALID_IRQ_MASK	0x1fffffff

#define NR_EP93XX_IRQS			(64 + 24)

#define EP93XX_BOARD_IRQ(x)		(NR_EP93XX_IRQS + (x))
#define EP93XX_BOARD_IRQS		32

#define NR_IRQS				(NR_EP93XX_IRQS + EP93XX_BOARD_IRQS)


#endif
