/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/*
 * arch/arm/mach-ks8695/include/mach/irqs.h
 *
 * Copyright (C) 2006 Simtec Electronics
 *   Ben Dooks <ben@simtec.co.uk>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASM_ARCH_IRQS_H
#define __ASM_ARCH_IRQS_H


#define NR_IRQS				32

/*
 * IRQ definitions
 */
#define KS8695_IRQ_COMM_RX		0
#define KS8695_IRQ_COMM_TX		1
#define KS8695_IRQ_EXTERN0		2
#define KS8695_IRQ_EXTERN1		3
#define KS8695_IRQ_EXTERN2		4
#define KS8695_IRQ_EXTERN3		5
#define KS8695_IRQ_TIMER0		6
#define KS8695_IRQ_TIMER1		7
#define KS8695_IRQ_UART_TX		8
#define KS8695_IRQ_UART_RX		9
#define KS8695_IRQ_UART_LINE_STATUS	10
#define KS8695_IRQ_UART_MODEM_STATUS	11
#define KS8695_IRQ_LAN_RX_STOP		12
#define KS8695_IRQ_LAN_TX_STOP		13
#define KS8695_IRQ_LAN_RX_BUF		14
#define KS8695_IRQ_LAN_TX_BUF		15
#define KS8695_IRQ_LAN_RX_STATUS	16
#define KS8695_IRQ_LAN_TX_STATUS	17
#define KS8695_IRQ_HPNA_RX_STOP		18
#define KS8695_IRQ_HPNA_TX_STOP		19
#define KS8695_IRQ_HPNA_RX_BUF		20
#define KS8695_IRQ_HPNA_TX_BUF		21
#define KS8695_IRQ_HPNA_RX_STATUS	22
#define KS8695_IRQ_HPNA_TX_STATUS	23
#define KS8695_IRQ_BUS_ERROR		24
#define KS8695_IRQ_WAN_RX_STOP		25
#define KS8695_IRQ_WAN_TX_STOP		26
#define KS8695_IRQ_WAN_RX_BUF		27
#define KS8695_IRQ_WAN_TX_BUF		28
#define KS8695_IRQ_WAN_RX_STATUS	29
#define KS8695_IRQ_WAN_TX_STATUS	30
#define KS8695_IRQ_WAN_LINK		31

#endif
