/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

/*
 * Apple Onboard Audio driver for tas codec (header)
 *
 * Copyright 2006 Johannes Berg <johannes@sipsolutions.net>
 *
 * GPL v2, can be found in COPYING.
 */
#ifndef __SND_AOA_CODECTASH
#define __SND_AOA_CODECTASH

#define TAS_REG_MCS	0x01	/* main control */
#	define TAS_MCS_FASTLOAD		(1<<7)
#	define TAS_MCS_SCLK64		(1<<6)
#	define TAS_MCS_SPORT_MODE_MASK	(3<<4)
#	define TAS_MCS_SPORT_MODE_I2S	(2<<4)
#	define TAS_MCS_SPORT_MODE_RJ	(1<<4)
#	define TAS_MCS_SPORT_MODE_LJ	(0<<4)
#	define TAS_MCS_SPORT_WL_MASK	(3<<0)
#	define TAS_MCS_SPORT_WL_16BIT	(0<<0)
#	define TAS_MCS_SPORT_WL_18BIT	(1<<0)
#	define TAS_MCS_SPORT_WL_20BIT	(2<<0)
#	define TAS_MCS_SPORT_WL_24BIT	(3<<0)

#define TAS_REG_DRC	0x02
#define TAS_REG_VOL	0x04
#define TAS_REG_TREBLE	0x05
#define TAS_REG_BASS	0x06
#define TAS_REG_LMIX	0x07
#define TAS_REG_RMIX	0x08

#define TAS_REG_ACR	0x40	/* analog control */
#	define TAS_ACR_B_MONAUREAL	(1<<7)
#	define TAS_ACR_B_MON_SEL_RIGHT	(1<<6)
#	define TAS_ACR_DEEMPH_MASK	(3<<2)
#	define TAS_ACR_DEEMPH_OFF	(0<<2)
#	define TAS_ACR_DEEMPH_48KHz	(1<<2)
#	define TAS_ACR_DEEMPH_44KHz	(2<<2)
#	define TAS_ACR_INPUT_B		(1<<1)
#	define TAS_ACR_ANALOG_PDOWN	(1<<0)

#define TAS_REG_MCS2	0x43	/* main control 2 */
#	define TAS_MCS2_ALLPASS		(1<<1)

#define TAS_REG_LEFT_BIQUAD6	0x10
#define TAS_REG_RIGHT_BIQUAD6	0x19

#define TAS_REG_LEFT_LOUDNESS		0x21
#define TAS_REG_RIGHT_LOUDNESS		0x22
#define TAS_REG_LEFT_LOUDNESS_GAIN	0x23
#define TAS_REG_RIGHT_LOUDNESS_GAIN	0x24

#define TAS3001_DRC_MAX		0x5f
#define TAS3004_DRC_MAX		0xef

#endif /* __SND_AOA_CODECTASH */
